/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewDoctorRouteImport } from './routes/preview-doctor'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as ApiPreviewDoctorRouteImport } from './routes/api/preview-doctor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDoctorRoute = PreviewDoctorRouteImport.update({
  id: '/preview-doctor',
  path: '/preview-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewDoctorRoute = ApiPreviewDoctorRouteImport.update({
  id: '/api/preview-doctor',
  path: '/api/preview-doctor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview-doctor': typeof PreviewDoctorRoute
  '/screens': typeof ScreensRoute
  '/api/preview-doctor': typeof ApiPreviewDoctorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview-doctor': typeof PreviewDoctorRoute
  '/screens': typeof ScreensRoute
  '/api/preview-doctor': typeof ApiPreviewDoctorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview-doctor': typeof PreviewDoctorRoute
  '/screens': typeof ScreensRoute
  '/api/preview-doctor': typeof ApiPreviewDoctorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preview-doctor' | '/screens' | '/api/preview-doctor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preview-doctor' | '/screens' | '/api/preview-doctor'
  id: '__root__' | '/' | '/preview-doctor' | '/screens' | '/api/preview-doctor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewDoctorRoute: typeof PreviewDoctorRoute
  ScreensRoute: typeof ScreensRoute
  ApiPreviewDoctorRoute: typeof ApiPreviewDoctorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-doctor': {
      id: '/preview-doctor'
      path: '/preview-doctor'
      fullPath: '/preview-doctor'
      preLoaderRoute: typeof PreviewDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview-doctor': {
      id: '/api/preview-doctor'
      path: '/api/preview-doctor'
      fullPath: '/api/preview-doctor'
      preLoaderRoute: typeof ApiPreviewDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewDoctorRoute: PreviewDoctorRoute,
  ScreensRoute: ScreensRoute,
  ApiPreviewDoctorRoute: ApiPreviewDoctorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
